spring:
  application:
    name: users-crud
  datasource:
    username: postgres
    password: pswd
    url: jdbc:postgresql://localhost:5432/users
  jpa:
    generate-ddl: true
config:
  age:
    min: 18
server:
  servlet:
    context-path: /api/v1
